import type { Club } from '~/schema/club';

export const clubs: Club[] = [
    {
        id: '1',
        name: 'Atlanta Hawks',
        logo: '/images/clubs-logo/atlanta-hawks-logo.png',
        banner: 'https://images.unsplash.com/photo-1546519638-68e109498ffc?w=800&h=400&fit=crop',
        visibility: 'public',
        location: 'Makati City, Metro Manila',
        history: new Date('1968-01-01'),
        rank: 'S',
        members: 85,
        matchesPlayed: 142,
        reviews: 89
    },
    {
        id: '2',
        name: 'Charlotte Hornets',
        logo: '/images/clubs-logo/charlotte-hornets-logo.png',
        banner: 'https://images.unsplash.com/photo-1574623452334-1e0ac2b3ccb4?w=800&h=400&fit=crop',
        visibility: 'public',
        location: 'Quezon City, Metro Manila',
        history: new Date('1988-01-01'),
        rank: 'A',
        members: 72,
        matchesPlayed: 98,
        reviews: 67
    },
    {
        id: '3',
        name: 'Chicago Bulls',
        logo: '/images/clubs-logo/chicago-bulls-logo.png',
        banner: 'https://images.unsplash.com/photo-1577223625816-7546f13df25d?w=800&h=400&fit=crop',
        visibility: 'private',
        location: 'Manila City, Metro Manila',
        history: new Date('1966-01-01'),
        rank: 'S',
        members: 45,
        matchesPlayed: 76,
        reviews: 52
    },
    {
        id: '4',
        name: 'Cleveland Cavaliers',
        logo: '/images/clubs-logo/cleveland-cavaliers-logo.png',
        banner: 'https://images.unsplash.com/photo-1546519638-68e109498ffc?w=800&h=400&fit=crop',
        visibility: 'public',
        location: 'Pasig City, Metro Manila',
        history: new Date('1970-01-01'),
        rank: 'B',
        members: 63,
        matchesPlayed: 134,
        reviews: 78
    },
    {
        id: '5',
        name: 'Los Angeles Lakers',
        logo: '/images/clubs-logo/los-angeles-lakers-logo.png',
        banner: 'https://images.unsplash.com/photo-1574623452334-1e0ac2b3ccb4?w=800&h=400&fit=crop',
        visibility: 'public',
        location: 'Taguig City, Metro Manila',
        history: new Date('1947-01-01'),
        rank: 'S',
        members: 95,
        matchesPlayed: 156,
        reviews: 134
    },
    {
        id: '6',
        name: 'Miami Heat',
        logo: '/images/clubs-logo/miami-heat-logo.png',
        banner: 'https://images.unsplash.com/photo-1577223625816-7546f13df25d?w=800&h=400&fit=crop',
        visibility: 'private',
        location: 'Mandaluyong City, Metro Manila',
        history: new Date('1988-01-01'),
        rank: 'A',
        members: 91,
        matchesPlayed: 187,
        reviews: 156
    },
    {
        id: '7',
        name: 'Milwaukee Bucks',
        logo: '/images/clubs-logo/milwaukee-bucks-logo.png',
        banner: 'https://images.unsplash.com/photo-1546519638-68e109498ffc?w=800&h=400&fit=crop',
        visibility: 'public',
        location: 'Parañaque City, Metro Manila',
        history: new Date('1968-01-01'),
        rank: 'S',
        members: 78,
        matchesPlayed: 145,
        reviews: 112
    },
    {
        id: '8',
        name: 'Phoenix Suns',
        logo: '/images/clubs-logo/phoenix-suns-logo.png',
        banner: 'https://images.unsplash.com/photo-1574623452334-1e0ac2b3ccb4?w=800&h=400&fit=crop',
        visibility: 'public',
        location: 'Las Piñas City, Metro Manila',
        history: new Date('1968-01-01'),
        rank: 'A',
        members: 82,
        matchesPlayed: 167,
        reviews: 143
    },
    {
        id: '9',
        name: 'Toronto Raptors',
        logo: '/images/clubs-logo/toronto-raptors-logo.png',
        banner: 'https://images.unsplash.com/photo-1577223625816-7546f13df25d?w=800&h=400&fit=crop',
        visibility: 'private',
        location: 'Muntinlupa City, Metro Manila',
        history: new Date('1995-01-01'),
        rank: 'B',
        members: 67,
        matchesPlayed: 123,
        reviews: 98
    },
    {
        id: '10',
        name: 'Washington Wizards',
        logo: '/images/clubs-logo/washington-wizards-logo.png',
        banner: 'https://images.unsplash.com/photo-1546519638-68e109498ffc?w=800&h=400&fit=crop',
        visibility: 'public',
        location: 'Marikina City, Metro Manila',
        history: new Date('1961-01-01'),
        rank: 'C',
        members: 58,
        matchesPlayed: 89,
        reviews: 67
    },
    {
        id: '11',
        name: 'Golden State Warriors',
        logo: '/images/clubs-logo/phoenix-suns-logo.png',
        banner: 'https://images.unsplash.com/photo-1574623452334-1e0ac2b3ccb4?w=800&h=400&fit=crop',
        visibility: 'public',
        location: 'San Juan City, Metro Manila',
        history: new Date('1946-01-01'),
        rank: 'S',
        members: 88,
        matchesPlayed: 178,
        reviews: 156
    },
    {
        id: '12',
        name: 'Boston Celtics',
        logo: '/images/clubs-logo/chicago-bulls-logo.png',
        banner: 'https://images.unsplash.com/photo-1577223625816-7546f13df25d?w=800&h=400&fit=crop',
        visibility: 'private',
        location: 'Pasay City, Metro Manila',
        history: new Date('1946-01-01'),
        rank: 'S',
        members: 92,
        matchesPlayed: 198,
        reviews: 178
    },
    {
        id: '13',
        name: 'Dallas Mavericks',
        logo: '/images/clubs-logo/milwaukee-bucks-logo.png',
        banner: 'https://images.unsplash.com/photo-1546519638-68e109498ffc?w=800&h=400&fit=crop',
        visibility: 'public',
        location: 'Caloocan City, Metro Manila',
        history: new Date('1980-01-01'),
        rank: 'A',
        members: 76,
        matchesPlayed: 134,
        reviews: 112
    },
    {
        id: '14',
        name: 'New York Knicks',
        logo: '/images/clubs-logo/cleveland-cavaliers-logo.png',
        banner: 'https://images.unsplash.com/photo-1574623452334-1e0ac2b3ccb4?w=800&h=400&fit=crop',
        visibility: 'public',
        location: 'Malabon City, Metro Manila',
        history: new Date('1946-01-01'),
        rank: 'B',
        members: 84,
        matchesPlayed: 156,
        reviews: 134
    },
    {
        id: '15',
        name: 'Denver Nuggets',
        logo: '/images/clubs-logo/atlanta-hawks-logo.png',
        banner: 'https://images.unsplash.com/photo-1577223625816-7546f13df25d?w=800&h=400&fit=crop',
        visibility: 'private',
        location: 'Navotas City, Metro Manila',
        history: new Date('1967-01-01'),
        rank: 'A',
        members: 79,
        matchesPlayed: 145,
        reviews: 123
    },
    {
        id: '16',
        name: 'Portland Trail Blazers',
        logo: '/images/clubs-logo/charlotte-hornets-logo.png',
        banner: 'https://images.unsplash.com/photo-1546519638-68e109498ffc?w=800&h=400&fit=crop',
        visibility: 'public',
        location: 'Valenzuela City, Metro Manila',
        history: new Date('1970-01-01'),
        rank: 'C',
        members: 65,
        matchesPlayed: 98,
        reviews: 76
    },
    {
        id: '17',
        name: 'Utah Jazz',
        logo: '/images/clubs-logo/miami-heat-logo.png',
        banner: 'https://images.unsplash.com/photo-1574623452334-1e0ac2b3ccb4?w=800&h=400&fit=crop',
        visibility: 'public',
        location: 'Pateros, Metro Manila',
        history: new Date('1974-01-01'),
        rank: 'B',
        members: 71,
        matchesPlayed: 123,
        reviews: 98
    },
    {
        id: '18',
        name: 'Sacramento Kings',
        logo: '/images/clubs-logo/los-angeles-lakers-logo.png',
        banner: 'https://images.unsplash.com/photo-1577223625816-7546f13df25d?w=800&h=400&fit=crop',
        visibility: 'private',
        location: 'Makati City, Metro Manila',
        history: new Date('1945-01-01'),
        rank: 'C',
        members: 58,
        matchesPlayed: 87,
        reviews: 65
    },
    {
        id: '19',
        name: 'Minnesota Timberwolves',
        logo: '/images/clubs-logo/toronto-raptors-logo.png',
        banner: 'https://images.unsplash.com/photo-1546519638-68e109498ffc?w=800&h=400&fit=crop',
        visibility: 'public',
        location: 'Quezon City, Metro Manila',
        history: new Date('1989-01-01'),
        rank: 'D',
        members: 42,
        matchesPlayed: 67,
        reviews: 45
    },
    {
        id: '20',
        name: 'Oklahoma City Thunder',
        logo: '/images/clubs-logo/washington-wizards-logo.png',
        banner: 'https://images.unsplash.com/photo-1574623452334-1e0ac2b3ccb4?w=800&h=400&fit=crop',
        visibility: 'private',
        location: 'Manila City, Metro Manila',
        history: new Date('2008-01-01'),
        rank: 'B',
        members: 73,
        matchesPlayed: 112,
        reviews: 89
    }
];
